pkg/device-plugin/register.go

DeviceMemoryScaling does not take effect。 Becase if deviceMemoryScaling equals 1.8, int32 type will change value to 1.

fix the deviceMemoryScaling type

---

charts/vgpu/templates/device-plugin/daemonsetmlu.yaml
charts/vgpu/templates/device-plugin/daemonsetnvidia.yaml
charts/vgpu/templates/scheduler/deployment.yaml
charts/vgpu/templates/scheduler/service.yaml
charts/vgpu/values.yaml
cmd/device-plugin/nvidia/main.go
cmd/scheduler/main.go
pkg/device-plugin/config/config.go
pkg/device-plugin/mlu/options.go
pkg/device-plugin/mlu/register.go
pkg/device-plugin/nvidiadevice/register.go
pkg/scheduler/config/config.go

The address and timeout parameters can remove in program and helm chart, as vgpu-scheduler is no longer used grpc to communicate with deviceplugin.

remove vgpu-scheduler grpc code

---

charts/vgpu/templates/device-plugin/daemonsetnvidia.yaml
charts/vgpu/values.yaml

k8s node may have multiple runtimes coexisting and nvidia-runtime is not the default runtime.But device-plugin needs to use nvidia-runtime，So provide a configuration item for users to configure.

helmChart: add runtimeClass for device-plugin daemonset

---

README.md
charts/vgpu/templates/scheduler/job-patch/job-createSecret.yaml
charts/vgpu/templates/scheduler/service.yaml
charts/vgpu/templates/scheduler/webhook.yaml
charts/vgpu/values.yaml

Some time we should custom webhook address instead of using  Service. for example,  k8s on k8s or vclusters.  we can't use  service discovery to let  work node  know the real scheduler's  addr.
This pr make project support this scene. custom webhook url and fixed schedulerPort to 31998

feature: support custom webhook url and generate it's certs

---

cmd/scheduler/main.go
pkg/util/util.go

klog verbose log level not working properly
before, no matter how we adjust the log level, the log will not be output.
https://github.com/4paradigm/k8s-vgpu-scheduler/blob/master/pkg/scheduler/scheduler.go#L136
```golang
klog.V(5).Infoln("Scheduler into RegisterFromNodeAnnotations")
```
klog flags need to be added to rootCmd flags

Fix klog verbose not working

---

cmd/scheduler/metrics.go

clean: fix node name typo

---

cmd/scheduler/metrics.go

修复两个metrics 对pod namespace label名称定义不统一的问题

fix the problem that two metrics services are not unified to namespace

---

pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
pkg/device-plugin/nvidiadevice/nvinternal/plugin/register_test.go

Failed to obtain numa information, the error message is as follows
```bash
E1214 10:59:54.986452    2829 register.go:86] "failed to get numa information" err="strconv.Atoi: parsing \"N/A\": invalid syntax" idx=0
```
/kind feature
Single Tesla P4， nvidia-smi topo info 
```bash
root@controller-node-1:/# nvidia-smi topo -m
GPU0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	0-7		N/A		N/A
Legend:
X    = Self
SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
PIX …
```

support mutiple gpu card numa

---

pkg/util/util.go

The real environment scheduler log is as follows. A lot of log information about EncodeNode is displayed on the screen. Increase the log output level and reduce useless information.
```bash
I0109 06:38:05.385637      27 scheduler.go:305] "Bind" pod="vgpu-test-5ccbbdf446-5h97f" namespace="default" podUID="fc9cfd90-f044-449d-a703-de27b982a492" node="tesla"
I0109 06:38:05.424852      27 nodelock.go:45] "Node lock set" node="tesla"
I0109 06:38:05.486448      27 scheduler.go:342] After Binding Process
I0109 06:38:16.942265      27 util.go:106] Encoded node Devices GPU-e290caca-2f0c-9582-acab-67a142b61ffa,10,7680,100,NVIDIA-Tesla P4,0,true:
I0109 06:38:31.507443      27 pods.go:62] vgpu-test-5ccbbdf446-qpzmm deleted
I0109 06:38:31.975420      27 util.go:106] Encoded node Devices …
```

reduce useless scheduler logs when Encoded node

---

pkg/scheduler/score.go

The current scheduling process is relatively black-box. Once scheduling fails, users have no way of knowing the specific reasons. At the same time, the logic of the scheduling selection card and the pod association are not enough. Therefore, try to output more logs during the scheduling process to facilitate user troubleshooting.
Previous scheduling log information
```bash
I0110 09:29:05.389816     207 scheduler.go:347] "begin schedule filter" pod="vgpu-test-dc87df5b4-6ndkz" uuid="f94a3a21-a348-4ca3-af74-cbda013eab0b" namespaces="default"
I0110 09:29:05.389891     207 scheduler.go:288] usage: pod vgpu-test-dc87df5b4-24r9c assigned tesla [[{0 GPU-e290caca-2f0c-9582-acab-67a142b61ffa NVIDIA 1000 100}]]67a142b61ffa","Index":0,"Used":1,"Count":10,"Usedmem":1000,"Totalmem":7680,"Totalcore":100, …
```

enhance schedule process logs

---

pkg/scheduler/scheduler.go

When `util.GetNode(val.Name)` returns an error, a panic will occur.

fix device-plugin panic

---

cmd/vGPUmonitor/metrics.go

集群规模：3600+个Pod
问题现象：采集device-plugin的metrics数据时，因为集群中Pod数量太多导致响应超时。
解决办法：使用informer缓存所有Pod，在比较uid时使用lister查询Pod。已测试通过。

bugfix: device-plugin monitor serves too slowly in big cluster

---

pkg/scheduler/scheduler.go

Problem description.
After the scheduler component restarts unexpectedly, some metrics are lost, which can only be obtained when the scheduling is triggered.
Solution
When scheduler starts, all node information is obtained and injected into scheduler object
The test results are as follows

fix: loss of metrics after vdeivce restart

---

charts/vgpu/templates/scheduler/deployment.yaml
charts/vgpu/values.yaml

If we install the nvidia-vgpu-scheduler as default scheduler, we need to remove the k8s defualt
scheduler pod from the cluster first, we must specified node name to skip the shcedule workflow.
And use the following helm command to install nvidia-vgpu-scheduler:
```shell
helm install nvidia-vgpu -n nvidia-vgpu  --create-namespaces \
--set schedulerName=default-scheduler \
--set scheduler.nodeName=<node_name> \
--set scheduler.kubeScheduler.image=<kube_scheduler> \
--set scheduler.kubeScheduler.tag=<kube_scheduler_tag> \
```

install nvidia-vgpu-schduler as default scheduler

---

charts/vgpu/templates/scheduler/deployment.yaml
charts/vgpu/values.yaml
cmd/scheduler/main.go
cmd/scheduler/metrics.go
pkg/scheduler/config/config.go

Why do we need the flage?
The metrics port is confilct with vGPU monitor if we deploy the scheduler with `HostNetwork` mode.
In the scenario, we want to deploy scheduler with k8s native scheduler in one static pod with `HostNetwork` mode. but the  vGPU monitor is same port with scheduler.

add metrics bind address flag for scheduler

---

charts/vgpu/templates/scheduler/webhook.yaml
charts/vgpu/values.yaml

fix #83
/kind feature
Add helm values parameter to provide users with the ability to set MutatingWebhookConfiguration failurePolicy. The default value is Ignore,this feature can solve the problem that when the nvidia-vgpu-webhook service is unavailable, the creation and restart of K8s system services (for example: calico cni) will not be affected.

support manual config MutatingWebhookConfiguration failurePolicy

---

charts/hami/templates/scheduler/configmap.yaml
charts/hami/templates/scheduler/configmapnew.yaml
charts/hami/templates/scheduler/deployment.yaml
charts/hami/values.yaml

in our scenario, we have instanlled component `scheduler-plugins` replace the kube-scheduer, and want only install the vgpu-scheduler as a extender. we need to suport this way to deploy vgpu scheduler only. 
the test results:
```shell
helm install hami -n hami-system ./charts/hami --create-namespace --set scheduler.kubeScheduler.enabled=false --dry-run
```

add a option to disable kube scheduler in chart

---

charts/hami/templates/device-plugin/monitorservice.yaml

current `device-plugin` Service label name is `app.kubernetes.io/component: 4pd-scheduler`, hope is `app.kubernetes.io/component: 4pd-device-plugin`
from this PR https://github.com/Project-HAMi/HAMi/pull/158 found this issue

update device plugin svc label name

---

charts/hami/templates/_helpers.tpl
charts/hami/templates/device-plugin/configmap.yaml
charts/hami/templates/device-plugin/daemonsethygon.yaml
charts/hami/templates/device-plugin/daemonsetmlu.yaml
charts/hami/templates/device-plugin/daemonsetnvidia.yaml
charts/hami/templates/device-plugin/monitorrole.yaml
charts/hami/templates/device-plugin/monitorrolebinding.yaml
charts/hami/templates/device-plugin/monitorservice.yaml
charts/hami/templates/device-plugin/monitorserviceaccount.yaml
charts/hami/templates/scheduler/configmap.yaml
charts/hami/templates/scheduler/configmapnew.yaml
charts/hami/templates/scheduler/deployment.yaml
charts/hami/templates/scheduler/job-patch/clusterrole.yaml
charts/hami/templates/scheduler/job-patch/clusterrolebinding.yaml
charts/hami/templates/scheduler/job-patch/job-createSecret.yaml
charts/hami/templates/scheduler/job-patch/job-patchWebhook.yaml
charts/hami/templates/scheduler/job-patch/psp.yaml
charts/hami/templates/scheduler/job-patch/role.yaml
charts/hami/templates/scheduler/job-patch/rolebinding.yaml
charts/hami/templates/scheduler/job-patch/serviceaccount.yaml
charts/hami/templates/scheduler/rolebinding.yaml
charts/hami/templates/scheduler/service.yaml
charts/hami/templates/scheduler/serviceaccount.yaml
charts/hami/templates/scheduler/webhook.yaml
charts/hami/values.yaml

from https://github.com/Project-HAMi/HAMi/issues/164
Rename hami helm charts and change the content of 4pd to hami
test result
Deploy the modified helm charts and all components run normally
```bash
➜  ~ helm list
NAME       	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART     	APP VERSION
nvidia-vgpu	default  	1       	2024-02-23 15:24:11.620889 +0800 CST	deployed	hami-2.0.0	0.0.2
➜  ~ helm get manifest nvidia-vgpu | grep 4pd
image: 4pdosc/vdcu-device-plugin:v1.0
Make sure that except for the hygonimage, all other 4pd-related modifications have been completed.
➜  ~ kubectl get po
NAME                                         READY   STATUS    RESTARTS   AGE
nvidia-vgpu-hami-device-plugin-2fjw4         2/2     Running   0          16m …
```

rename helm chart 4pd to hami

---

pkg/device/cambricon/device.go
pkg/device/hygon/device.go
pkg/device/nvidia/device.go
pkg/util/nodelock/nodelock.go
pkg/util/types.go

from https://github.com/Project-HAMi/HAMi/issues/164
Rename hami golang code and change the content of `4pd.io` to `hami.io`
test results
we can find the node annotations has been change by use the latest device-plugin binrary
```bash
➜  ~ kubectl describe no controller-node-1 | grep 'hami.io'
hami.io/node-handshake: Reported 2024-02-27 14:11:45.338336866 +0000 UTC m=+30.239803637
hami.io/node-nvidia-register: GPU-e290caca-2f0c-9582-acab-67a142b61ffa,10,7680,100,NVIDIA-Tesla P4,0,true:
```
Deploy demo and vgpu is successfully allocated
```bash
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app: gpu-test
name: gpu-test
namespace: default
spec:
replicas: 1
selector:
matchLabels:
app: gpu-test
template:
metadata:
labels:
app: gpu-test
spec:
containers:
- …
```

rename golang code 4pd to hami

---

cmd/vGPUmonitor/main.go
cmd/vGPUmonitor/metrics.go
go.mod
go.sum
pkg/device/devices.go
pkg/device/iluvatar/device.go
pkg/util/client/client.go

`k8s.io/klog` has been deprecated and replaced by `k8s.io/klog/v2`

replace k8s.io/klog with k8s.io/klog/v2

---

pkg/util/client/client.go

if the client is failed to init, the nil err will be throwed when using it.

throw the err when initing client

---

charts/hami/templates/scheduler/deployment.yaml
charts/hami/values.yaml
cmd/scheduler/main.go
docs/config.md
docs/config_cn.md
pkg/device/nvidia/device.go
pkg/device/nvidia/device_test.go
pkg/scheduler/config/config.go

It mainly simplifies user settings of resource limits. By default, the core and memory in one GPU are used.
issue: https://github.com/Project-HAMi/HAMi/issues/171

add default gpu num value

---

pkg/util/types.go
pkg/util/util.go
pkg/util/util_test.go

fix `EncodePodSingleDevice` method, when one pod having more then one container use device, this method encode device string will error.
- add many case to run unit tests.
- fix this bug.
- use const `OneContainerMultiDeviceSplitSymbol` and `OnePodMultiContainerSplitSymbol` to replace hardcode.

fix EncodePodSingleDevice method

---

.github/dependabot.yml
.github/workflows/close-stale-issues-pr.yaml

for these cases:
1. the number of isseus is increasing because issue has not been answered for a long time.
2. The package version is not updated in time
the robot can help us to marks as stale for issue not been answered for 30 days and close the issue after 14 days. like this:
and pull a request to upgrade the latest version for go mod and actions, like this:

add robot to cleanup stale issue and upgrade the latest version for go mod and actions

---

pkg/k8sutil/pod_test.go
pkg/scheduler/score.go
pkg/scheduler/score_test.go

Fixes: https://github.com/Project-HAMi/HAMi/issues/212
Fixes: https://github.com/Project-HAMi/HAMi/issues/198
When multi-container doesn't have to use device resources,  fix the index out of range.

fix: when container nou user device resource index out of range

---

pkg/device-plugin/hygon/dcu/server.go
pkg/device-plugin/mlu/server.go
pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
pkg/device/devices.go
pkg/device/nvidia/device.go
pkg/util/types.go
pkg/util/util.go
pkg/util/util_test.go

Fixes: https://github.com/Project-HAMi/HAMi/issues/212#issuecomment-2007150458
Kubelet is a loop to allocate GPU devices for multiple container requests using GPU resources, currently in `PodAllocationTrySuccess` method will check whether need release node lock, but `hami.io/devices-to-allocate` this annotation key is not use, so check failed, because current key is use `hami.io/vgpu-devices-to-allocate`.

fix: when multi container use device allocate fail

---

cmd/scheduler/main.go
pkg/scheduler/nodes.go
pkg/scheduler/scheduler.go

1. Add a node informer. To notify the scheduler of cache updates. Faster discovery of new nodes and removal of old nodes.  
2. When there is no device on a node in the scheduling cache, remove it from the scheduling cache to avoid scheduling pods to these nodes.

Optimize scheduling cache. Accelerate the discovery and deletion of nodes

---

charts/hami/templates/device-plugin/daemonsethygon.yaml
charts/hami/templates/device-plugin/daemonsetnvidia.yaml
cmd/device-plugin/mlu/main.go
cmd/device-plugin/nvidia/vgpucfg.go
pkg/device-plugin/hygon/dcu/register.go
pkg/device-plugin/mlu/server.go
pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
pkg/util/types.go

Define`NodeNameEnvName` const type and all env use this var to read node name.
Fixes: https://github.com/Project-HAMi/HAMi/issues/103

Use NODE_NAME as an environment variable uniformly

---

pkg/device/nvidia/device.go
pkg/device/nvidia/device_test.go

`default-gpu` is defined in two files, so there will be values that cannot be configured by the user. remove a define in `device.go` file.
issue: https://github.com/Project-HAMi/HAMi/issues/171

Remove redundant assignment code for DefaultResourceNum

---

pkg/scheduler/scheduler.go

/kind bug
When a node cannot bind, it should stop scheduling pods to that node
Part of https://github.com/Project-HAMi/HAMi/issues/272
When the lock hasn't expired yet.
the log of kube-scheduler
```
│ kube-scheduler I0417 07:44:16.769658       1 schedule_one.go:794] "Failed to bind pod" pod="default/gpu-brun-high-5959f868c8-4qnlr"                                                                                                                                                                                      │
│ kube-scheduler E0417 07:44:16.769797       1 scheduler.go:367] "Error scheduling pod; retrying" err="binding rejected: node node6 has been …
```

fix: When a node cannot bind, it should stop scheduling pods to that node

---

charts/hami/templates/scheduler/deployment.yaml
charts/hami/values.yaml

Cureent kube-scheduler and scheduler-extender can't run more than one pod because they do not use leader election, This PR adds `leaderElect` to controller `kube-scheduler` and `hami-scheduler` servers, whether use leader election.  default: use helm `.Release.Namespace` value to set `leader-elect-resource-namespace`.
Fixes: https://github.com/Project-HAMi/HAMi/issues/195
Test:
-  Start two scheduler pods; only one pod can execute the scheduler flow.
- Start three use gpu pods that can running success.

scheduler server add leader elect

---

cmd/device-plugin/nvidia/main.go
cmd/device-plugin/nvidia/vgpucfg.go

/kind bug
HAMi use `util.NodeName` before init. we need init first
Fixes #

fix nvidia device plugin nodename init sort error

---

pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go

/kind bug
fix https://github.com/Project-HAMi/HAMi/issues/169
Failed to get numa information. There is no need to crash the device-plugin. It is more reasonable to directly output the error log.
Fixes #

fix device plugin crash when  failed to get numa information

---

cmd/device-plugin/nvidia/main.go

/kind bug
At present, the device-plugin code will be swallowed if there is an exception when exiting and will not return. This should be fixed.
Fixes #

avoid swallowing exception when device-plugin exit, it should be thrown

---

pkg/device/nvidia/device.go
pkg/device/nvidia/device_test.go

At present, the selection of GPU type can be matched with device type by commenting `nvidia.com/use-gputype` and `nvidia.com/nouse-gputype` , similar to black and white lists,  But both cannot take effect simultaneously. 
The code uses substring matching as a filtering criterion，this may lead to users wanting to use A10 type GPUs, but ultimately being assigned to A100
To solve this problem, we can use `nvidia.com/use-gputype` and `nvidia.com/nouse-gputype` together
```yaml
metadata.:
annotations:
nvidia.com/use-gputype: A10
nvidia.com/nouse-gputype: A100
```
This specifies the required device types and excludes unnecessary device types

fix gpu type matching mechanism,  Enable the combination of GPUInUse and GPUNoUse

---

pkg/device/hygon/device.go
pkg/device/nvidia/device.go

/kind bug
before:
```
apiVersion: v1
kind: Node
metadata:
annotations:
NVIDIA: Deleted_2024.05.27 09:30:07
hami.io/node-handshake: Requesting_2024.05.27 09:48:48
hami.io/node-nvidia-register: 'GPU-26a583dd-542e-09bb-5dd1-9cc5bd6eb552,10,16384,200,NVIDIA-Tesla
```
after:
```
apiVersion: v1
kind: Node
metadata:
annotations:
hami.io/node-handshake: Deleted_2024.05.27 09:30:07
hami.io/node-nvidia-register: 'GPU-26a583dd-542e-09bb-5dd1-9cc5bd6eb552,10,16384,200,NVIDIA-Tesla
```
Fixes #
https://github.com/Project-HAMi/HAMi/blob/master/pkg/util/util.go#L347-L357
It can be seen that the `handshake` is used to determine whether the device is healthy.
**Does …

The annotation of the device that has been deleted is incorrect.

---

pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
pkg/util/util.go

/kind feature
During the device allocation phase, we only need to fetch the pods of the current node, not all pods, so we can podListOptions to filter accurately and improve efficiency.
Fixes #

enhance get current node pendding pods

---

pkg/scheduler/nodes.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/util/types.go

/kind feature
The scheduler heavily relies on a temporary memory variable `nodeInfoCopy`. When the scheduler unexpectedly restarts, the value of `nodeInfoCopy` will be lost, causing the scheduler to malfunction.
This PR has optimized this issue by removing the scheduler's dependency on the `nodeInfoCopy` variable.
Fixes #272

[Optimization] Fix the issue where scheduling can still occur on the node when the device-plugin crashes.

---

docs/gpu-dashboard.json

/kind feature
Gpu usage for pod latitude was previously added, but there are no related panels in Dashboard
Fixes #341 

add pod utilization dashboard

---

charts/hami/templates/scheduler/webhook.yaml
charts/hami/values.yaml

…amespaces
The code changes in `webhook.yaml` modify the namespace whitelist for the webhook. The `kube-system` and `istio-system` namespaces are added to the whitelist. This change aims to allow the webhook to function properly in these namespaces.
The purpose of this change is to whitelist `kube-system` and `istio-system` namespaces, following [Kubernetes best practices for webhooks](https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers/#avoiding-operating-on-the-kube-system-namespace). This prevents the Kubernetes system components and Istio components from being unnecessarily intercepted and possibly affected by our application's webhook.  …

feat: Update webhook.yaml to whitelist kube-system and istio-system 

---

docs/gpu-dashboard.json

Fix HostGPUMemoryUsage wrong unit on grafana dashboard
ie:
my metric is 500MiB, but grafana dashboard will show me almost 500TiB
/kind bug
Fixes #

Fix HostGPUMemoryUsage wrong unit

---

charts/hami/templates/scheduler/deployment.yaml
charts/hami/values.yaml
pkg/scheduler/scheduler.go
pkg/scheduler/utils.go
pkg/scheduler/utils_test.go

The code changes in `deployment.yaml` add the GPU node selector to the scheduler deployment. This change allows the scheduler to select nodes with the `gpu` label set to `"on"`. The environment variables are updated accordingly to include the `NODE_SELECTOR_GPU` variable.
/kind feature
This PR introduces a new feature to enhance our scheduler by allowing it to filter BM (Bare Metal) nodes based on a node selector. This is particularly useful in our cluster environment where only BM nodes have GPUs, ensuring that tasks requiring GPUs are scheduled appropriately. 
Fixes # https://github.com/Project-HAMi/HAMi/issues/375
**Does this PR introduce a …

feat: Add GPU node selector to scheduler deployment

---

pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go

Because we have not implemented the `GetPreferredAllocation()` function logic, in order to reduce the number of API calls to kubelet and device-plugin, set `GetPreferredAllocationAvailable` to false.
Fixes # https://github.com/Project-HAMi/HAMi/issues/414

disable PreferredAllocation

---

go.mod
pkg/scheduler/event.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind feature
Current, if a pod schedule fails, it's too difficult to troubleshoot, because the pod doesn't have the scheduler event .
This feature wants to add the scheduler process(filter and binding) event to accolated the pod
Sure. Currently, the event of all filters and bindings that do not meet the conditions are not detailed enough. They can be enhance later.
Test results
```
(base) ➜  scheduler git:(master) ✗ kubectl describe  po nginx-deployment-7bd89f854c-5p2xv
Name:             nginx-deployment-7bd89f854c-5p2xv
Namespace:        default
Priority:         0
Service Account:  default
...
...
...
Events:
Type    Reason            Age   From            Message
----    ------            ----  ---- …
```

add event handlers registration

---

README.md
README_cn.md
docs/how-to-use-volcano-vgpu.md

vgpu feature consists of several parts such as HAMi core, volcano-vgpu-device-plugin and scheduler. How to coordinate these parts to help user to enable it easier is so important especially for latest enhancement like vgpu binpacking and spreading ability.
This PR is adding the readme to guide user to enable vgpu with volcano more easier.
Fixes #355

add vgpu doc and update the readme.

---

charts/hami/templates/device-plugin/monitorservice.yaml
charts/hami/templates/scheduler/configmap.yaml

/kind bug
fix duplicate resource keys in scheduler's configmap
Fixes #
No

fix: fix duplicate resource keys in configmap

---

docker/Dockerfile

/kind bug
Changes introduced by this pr https://github.com/Project-HAMi/HAMi/pull/492
This PR modifies the final base image of hami from `nvidia/cuda:12.4.1-base-ubuntu22.04` to `nvidia/cuda:12.2.0-devel-ubuntu20.04`, and the image size becomes 3.1G.
We only need the image `nvidia/cuda:12.4.1-base-ubuntu22.04`
Fixes #

Fix HAMi image is too large and uses inappropriate base image

---

charts/hami/templates/device-plugin/configmap.yaml
cmd/device-plugin/nvidia/main.go
cmd/device-plugin/nvidia/vgpucfg.go
pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
pkg/device-plugin/nvidiadevice/nvinternal/rm/nvml_manager.go
pkg/util/types.go
pkg/util/util.go
pkg/util/util_test.go

/kind feature
When there are multiple cards in a cluster, the user only wants to manage certain cards.
Fixes # https://github.com/Project-HAMi/HAMi/issues/491
Users can customer decide whether device-plugin should filter certain devices, whether it is due to equipment failure or other reasons.

Feat: add filter device when register node by uuid or index

---

pkg/device/iluvatar/device.go
pkg/device/iluvatar/device_test.go

/kind bug
fix: error 'index out of range [1] with length 1' happen when allocate iluvatar device
fix: exception occurred while creating multiple pods with iluvatar gpu concurrently
Fixes #

fix: error happen when allocate iluvatar device

---

pkg/device-plugin/nvidiadevice/nvinternal/rm/health.go

/kind bug
Fix code scanning alert-Incorrect conversion between integer types
Fixes #551

Fix code scanning alert-Incorrect conversion between integer types

---

pkg/scheduler/webhook.go
pkg/scheduler/webhook_test.go

/kind bug
Fix pod assignment issue when pod already has a node assigned
Fixes #488

Fix pod assignment issue when pod already has a node assigned

---

pkg/k8sutil/pod_test.go
pkg/scheduler/score.go
pkg/scheduler/score_test.go

/kind bug
This PR fixes a bug in the scheduler where an array out-of-bounds error occurs when a GPU container is placed between non-GPU containers in a multi-container Pod. The bug manifests when the GPU container must be positioned at the beginning or end of the container list, otherwise, it leads to a panic with an array index error. Ensuring that the length of `score.Devices[idx]` is sufficient before appending resolves this issue. The scheduler now handles this scenario by extending the `score.Devices` array correctly.
Fixes #571 
None
None

fix(scheduler): prevent array out-of-bounds when GPU containers are placed between non-GPU containers

---

benchmarks/README.md

Correct the deployments path from HAMi/deployments to HAMi/benchmarks/deployments.
Fixes #

docs: fix deployments path in README

---

charts/hami/templates/_helpers.tpl
charts/hami/templates/scheduler/deployment.yaml
charts/hami/templates/scheduler/device-configmap.yaml
charts/hami/values.yaml
docs/config.md

/kind bug
This PR fixes an issue where Kubernetes version strings with additional metadata (e.g., `+k3s1`) caused problems in dynamically generated image tags. The new `strippedKubeVersion` function removes the part after the `+` in the Kubernetes version string, ensuring consistent and predictable image tagging.
Fixes #621
@archlitchi
@wawa0210
Yes, this PR restores compatibility for specifying certain parameters during `helm install/upgrade`. 
After version 2.4.1, users were unable to specify parameters like `scheduler.kubeScheduler.tag` (scheduler image version), `devicePlugin.deviceSplitCount`, …

Fix Kubernetes version string handling by stripping metadata

---

charts/hami/templates/device-plugin/daemonsetnvidia.yaml
charts/hami/values.yaml

/kind feature
DevicePlugin pod restart will cause business pod restart, this behavior is destructive.
We can provide users with the option to confirm the policy of rolling updates of deviceplugin
Fixes #627
Users can modify the update policy, and the default is rolling update

feat: support device plugin daemonset update strategy

---

pkg/scheduler/scheduler_test.go

/kind test
add uttest for scheduler/getPodUsage func

add ut for the scheduler

---

.github/ISSUE_TEMPLATE/config.yml

- Adds a FAQ link to the issue templates for better user guidance and to reduce repetitive questions.
Fixes #
@archlitchi If there are no issues with this PR, please pin the FAQ Issue to the top of the Issues list.
No

docs(issue-tmpl): add FAQ link to issue templates

---

pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go

/kind bug
This pr add filter device registry to node allocated resources https://github.com/Project-HAMi/HAMi/pull/495, but node annotation `hami.io/node-nvidia-register` values is not update. 
because define`idx := 0`,  cause  default index from 0 to `len(devs)`，maybe user filter device index is 0.
Fixes #

fix: filter device registry to node

---

pkg/scheduler/score_test.go

/kind bug
From the race process, the cause is that two tests in a package have write and read operations on the same map, resulting in concurrency issues.
Currently, the write operation of the map is initialized in TestMain to avoid simultaneous reading and writing.
Fixes # https://github.com/Project-HAMi/HAMi/actions/runs/12136056293/job/33836479355?pr=673

optimization map init in test

---

cmd/vGPUmonitor/metrics.go
pkg/monitor/nvidia/cudevshr.go
pkg/util/util.go

Optimize monitor time-consuming
Fixes #
https://github.com/Project-HAMi/HAMi/issues/672

Optimize monitor

---

charts/hami/templates/device-plugin/daemonsetnvidia.yaml

fix(helm): Add NODE_NAME env var to the vgpu-monitor container from spec.nodeName

---

pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
pkg/util/util.go
pkg/util/util_test.go

/kind bug
Fixes #
deviceidx is always is zero.

fix vGPUmonitor deviceidx is always 0

---

pkg/device/ascend/device.go
pkg/device/ascend/device_test.go

/kind bug
fix: exception occurred while creating multiple pods with ascend gpu concurrently
Fixes #

fix: exception happen when creating multiple ascend-gpu pods concurrently

---

examples/nvidia/specify_card_type_not_use.yaml
examples/nvidia/specify_card_type_to_use.yaml
examples/nvidia/specify_uuid_not_use.yaml
examples/nvidia/specify_uuid_to_use.yaml

add detail comment for nvidia specify card case.
add detail comment to nvidia specify card case to be more user-friendly. avoid wrong use，like https://github.com/Project-HAMi/HAMi/issues/707
Fixes #

fix example yaml

---

pkg/device/cambricon/device_test.go

/kind test
add ut for device/cambricon

add ut for device/cambricon

---

README.md
README_cn.md
docs/develop/tasklist.md
example.yaml
examples/nvidia/default_use.yaml
examples/nvidia/default_use_legacy.yaml
examples/nvidia/example.yaml
examples/nvidia/specify_card_type_not_use.yaml
examples/nvidia/specify_card_type_to_use.yaml
examples/nvidia/specify_scheduling_policy.yaml
examples/nvidia/specify_uuid_not_use.yaml
examples/nvidia/specify_uuid_to_use.yaml
examples/nvidia/use_as_normal.yaml
examples/nvidia/use_exclusive_card.yaml
examples/nvidia/use_memory_fraction.yaml
examples/nvidia/use_sharing_card.yaml

Add usage examples for GPU sharing in readme for newers
Help avoiding #661 #590
- See more info in: https://github.com/Project-HAMi/HAMi/issues/590#issuecomment-2510661848
- Unify the unit of `nvidia.com/gpumem` in examples to M.
**Does this PR introduce a user-facing change?**: no

doc(README): add examples for GPU sharing and update-examples

---

pkg/scheduler/scheduler.go
pkg/scheduler/score.go
pkg/scheduler/score_test.go

feat: Return the nodes that failed to be scheduled back to the scheduler
/kind feature
According to the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/1819-scheduler-extender/README.md) requirements, nodes that cannot be scheduled should be returned to the scheduler.
Fixes #
When there is no node in the cluster that meets the scheduling requirements, HAMi currently does not return any information to the scheduler, which does not meet the KEP specifications. According to the KEP requirements, the information of nodes that do not meet the requirements and the errors should be returned to the scheduler.
**Does this PR …

feat: Return the nodes that failed to be scheduled back to the scheduler

---

pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go

There is no configurable klog log level parameter available at the startup of the device plugin, so this log will not be printed.

fix(log): fix missing log output in nvidiadeviceplugin server

---

charts/hami/templates/device-plugin/daemonsetnvidia.yaml
charts/hami/templates/scheduler/deployment.yaml
charts/hami/values.yaml

/kind feature
Support setting the resources requests and limits of pods during helm charts installation.
Fixes #738 
Default request 
Test result:
1. Helm charts  installation with default values, resources is empty.
```yaml
Pro HAMi % kubectl -n hami-system get daemonset.apps/hami-device-plugin -oyaml | grep resources -C 1
name: device-plugin
resources: {}
securityContext:
--
name: vgpu-monitor
resources: {}
securityContext:
```
```yaml
Pro HAMi % kubectl -n hami-system get deployment.apps/hami-scheduler -oyaml | grep resources -C 5
- --leader-elect-resource-name=hami-scheduler
- --leader-elect-resource-namespace=hami-system
image: …
```

support configuration resources limits and requests

---

cmd/device-plugin/nvidia/main.go
cmd/scheduler/main.go
pkg/util/flag/flags.go
pkg/util/flag/flags_test.go

/kind enhancement
Print flags for device-plugin and scheduler.
Fixes #755 
The output  as follows：
For device-plugin:
```shell
I1229 17:11:54.537866   13477 flags.go:21] FLAG: --mig-strategy=""
I1229 17:11:54.537921   13477 flags.go:21] FLAG: --fail-on-init-error="true"
I1229 17:11:54.537929   13477 flags.go:21] FLAG: --nvidia-driver-root="/"
I1229 17:11:54.537934   13477 flags.go:21] FLAG: --pass-device-specs="false"
I1229 17:11:54.537939   13477 flags.go:21] FLAG: --device-list-strategy="[envvar]"
I1229 17:11:54.537945   13477 flags.go:21] FLAG: --device-id-strategy="uuid"
I1229 17:11:54.537948   13477 flags.go:21] FLAG: --gds-enabled="false"
I1229 17:11:54.537951   13477 flags.go:21] …
```

print flags for device-plugin and scheduler

---

.github/workflows/ci-image-scanning.yaml
.github/workflows/ci.yaml

/kind cleanup
This pull request includes changes to the CI workflows to streamline the installation of Go by using the version specified in the `go.mod` file instead of hardcoding the version number.
Changes to CI workflows:
* [`.github/workflows/ci-image-scanning.yaml`](diffhunk://#diff-98257f4321f494a80de3c4360b3eb1a01154102803728fee435cdf14bd657ad0L42-R42): Updated the Go installation to use the version specified in `go.mod` instead of a hardcoded version.
* [`.github/workflows/ci.yaml`](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL32-R32): Updated multiple instances of Go installation to use the version specified in `go.mod` instead of a hardcoded version. [[1]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c310 …

refactor(ci): use go.mod file for Go version in workflows

---

charts/hami/values.yaml
cmd/device-plugin/nvidia/main.go

/kind feature
Support setting log level for device-plugin.
Fixes #770 
Add `version` sub command to print the current version info, the `-v` parameter is used to control the log level.
```shell
Pro tmp % ./nvidia-device-plugin version    // print version 
NVIDIA Device Plugin version: v0.12
```
```shell
Pro tmp % ./nvidia-device-plugin --v=4  // set log level
```

support set log level for device plugin

---

charts/hami/templates/device-plugin/daemonsetnvidia.yaml
docker/Dockerfile
docker/Dockerfile.withlib
docker/vgpu-init.sh
pkg/device-plugin/nvidiadevice/nvinternal/info/version.go
pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
pkg/device-plugin/nvidiadevice/nvinternal/plugin/util.go

The most important reason that restarts affect business is that libvgpu.so is rewritten, leading to the application loading a partially written .so file. Currently, an MD5 calculation is used to determine if the file is the same, and it is not rewritten if it is different.
Fixes #
Test:
OCI config:
Pod: 

feat: Restart/Upgrade device-plugin will not affect services.

---

Makefile
docker/Dockerfile
docker/Dockerfile.withlib

/kind bug
Fixes #777
The image created by GitHub Action does not have VERSION information.
The reason is that the VERSION was not passed during the make all phase.

fix: nvidia-device-plugin no version info

---

charts/hami/templates/scheduler/service.yaml

What type of PR is this?
/kind bug
What this PR does / why we need it:
The targetPort specified in the service.yaml is hardcoded, while the metricsBindAddress is configurable, leading to inconsistent behavior. Additionally, the metrics interface should ideally be exposed at 0.0.0.0, so flexible configuration may not be necessary. Therefore, it is recommended to optimize this to metricsBindPort.
I have successfully tested it locally
Which issue(s) this PR fixes:
Fixes https://github.com/Project-HAMi/HAMi/issues/793
Special notes for your reviewer:
Does this PR introduce a user-facing change?:

optimize MetricsBindAddress to MetricsBindPort

---

README.md
README_cn.md

`glibc >= 2.17 & glibc < 2.3.0` probably typo, guessing the correct version would be 2.30.
Reference Links: https://sourceware.org/glibc/wiki/Glibc%20Timeline

[docs] fix: glibc version requirement in README

---

.github/workflows/call-e2e.yaml
hack/deploy-helm.sh
hack/util.sh

Fix E2E failure with pod status check

---

charts/hami/templates/device-plugin/daemonsetnvidia.yaml
cmd/vGPUmonitor/feedback.go
cmd/vGPUmonitor/main.go
cmd/vGPUmonitor/metrics.go

/kind flake
This pull request includes significant changes to the `vGPUmonitor` application to improve its structure and functionality. The most important changes include the addition of context and signal handling, the restructuring of the metrics collection process, and the refactoring of the `watchAndFeedback` function to support graceful shutdowns.
* [`cmd/vGPUmonitor/main.go`](diffhunk://#diff-093602e3776eeab4544178697b6844906795d96cfede8a687dc0bd52062cd4a7R20-R172): Added context and signal handling to enable graceful shutdown of the application. This includes capturing system signals and using a context to manage the lifecycle of goroutines.
* [`cmd/vGPUmonitor/metrics.go`](diffhunk://#diff-86cb3efac109940fd40fd28386ff0562af4fc73a4aab9e66d5aa19d2b53a7696 …

fix: Enhance GPU metrics collection and error handling in vGPU monitor

---

charts/hami/templates/device-plugin/monitorservice.yaml
charts/hami/templates/scheduler/service.yaml
charts/hami/values.yaml

/kind design
- Ports and Service types are now dynamically configured using values.yaml, making the charts more flexible and easier to customize.
- Default values are provided for httpPort, monitorPort, and nodePort to ensure backward compatibility.
- Hardcoded values for ports and nodePorts have been replaced with dynamic references to values.yaml.
- Added comments to explain the purpose of each section, making the templates easier to understand and maintain.
These changes are necessary to make the Helm charts more adaptable to different deployment scenarios and easier to maintain in the long term
Fixes #
This PR focuses on optimizing the Service …

refactor: update service configurations for device plugin and scheduler

---

pkg/scheduler/pods.go

/kind cleanup
klog.KRef will print out the pod name and namespace without adding separate fields
Fixes #

Remove duplicate log fields

---

docs/config.md
docs/config_cn.md

[docs] Fix default nvidia.resourceCoreName value in config.md

---

charts/hami/templates/_helpers.tpl
charts/hami/templates/scheduler/configmapnew.yaml
charts/hami/templates/scheduler/deployment.yaml
charts/hami/templates/scheduler/job-patch/job-createSecret.yaml
charts/hami/templates/scheduler/job-patch/job-patchWebhook.yaml

/kind bug
The current master branch was not able to handle version strings like **v1.30.8-eks-2d5f260** which is prevalent for AWS EKS. This causes HAMi charts installation failure as the minor version checking condition defaults to false and old parameters are used.
Also currently, scheduler imageTag needs to be set every time we have versions like **v1.30.8-eks-2d5f260**. However changing the definition of **strippedKubeVersion** in _helpers.tpl to a more general regexReplaceAll command solves this while being backwards compatible.
Fixes #
https://github.com/Project-HAMi/HAMi/issues/744
https://github.com/Project-HAMi/HAMi/issues/791
**Special notes for your reviewer**: This PR will …

Fix: Update handling of version strings in Helm template and helpers.tpl

---

charts/hami/values.yaml

/kind bug
Sets `passDeviceSpecsEnabled` to `false` by default in the device plugin to prevent pod startup failures in certain environments.
While `passDeviceSpecsEnabled=true` can help solve GPU access issues during runtime (especially in systemd-managed environments), it may cause pod startup failures in some cases (see #867 #776). Users who need this feature can still explicitly enable it through Helm values.
Fixes #867 #776
- Default value changed from `true` to `false`
- No functional changes to the feature itself
YES
NOTE: This is a breaking change for users who rely on the current default …

fix: Set passDeviceSpecsEnabled to false by default in device plugin

---

AUTHORS.md
CODE_OF_CONDUCT.md
MAINTAINERS.md

fixes broken community links:
- `CONTRIBUTOR_LADDER.md` -> `community-membership.md` as changed in https://github.com/Project-HAMi/community/commit/a557d69e4d4c42656ce6bef3c3e0043fc78b4944 / https://github.com/Project-HAMi/community/pull/8
- `CODE_OF_CONDUCT.md` -> `CODE-OF-CONDUCT.md` as changed in https://github.com/Project-HAMi/community/commit/fcb1d1cd86c5d7d296fdd18364df1b70a9e96135 / https://github.com/Project-HAMi/community/pull/7
n/a
none
no source code changes. fixes broken community links in the docs

docs: fix broken commmunity links

---

charts/hami/templates/scheduler/device-configmap.yaml
charts/hami/values.yaml
docs/config.md
docs/config_cn.md
pkg/device/nvidia/device.go

/kind feature
Fixes https://github.com/Project-HAMi/HAMi/issues/875
1. config `gpuCorePolicy` to `nvidia-vgpu-hami-scheduler-device` configmap, values is `defaule`、`force`、`disable`.
2. create use nvidia gpu will automatic injected to container env.

add config gpu core isolation policy for webhook

---

charts/hami/templates/scheduler/deployment.yaml
charts/hami/values.yaml

/kind feature
Enhance the stability of the scheduler
Fixes #877
When the scheduler replicas > 1 and leaderElect is on, each instances will try to create or acquire the lease resource. Instance which acquires the lease will become the leader of the scheduler cluster. It will be responsible for handling scheduling tasks, making decisions on resource allocation, and coordinating the overall scheduling operations.
Meanwhile, the non - leader instances will be in a standby state, monitoring the leader's activities. If the leader fails or loses the lease for some reason, these standby instances will compete again to acquire the lease and take over the …

feat: support scheduler replicas > 1

---

pkg/device/mthreads/device.go

/kind cleanup
This PR fixes typos
Fixes #
No functional changes to the code, just improvements to comments and log readability.

typo: fix typos in log and comment

---

cmd/device-plugin/nvidia/main.go
cmd/scheduler/main.go
pkg/device/cambricon/device_test.go
pkg/device/hygon/device_test.go
pkg/device/nvidia/device.go
pkg/scheduler/config/config.go
pkg/util/client/client.go
pkg/util/client/client_test.go

/kind feature
dd kube-qps and kube-burst parameters
Fixes #745
Depends on PR https://github.com/Project-HAMi/HAMi/pull/681

feat: Add kube-qps and kube-burst parameters.

---

charts/hami/templates/_helpers.tpl
charts/hami/templates/device-plugin/configmap.yaml
charts/hami/templates/device-plugin/daemonsetnvidia.yaml
charts/hami/templates/device-plugin/monitorrolebinding.yaml
charts/hami/templates/device-plugin/monitorservice.yaml
charts/hami/templates/device-plugin/monitorserviceaccount.yaml
charts/hami/templates/scheduler/configmap.yaml
charts/hami/templates/scheduler/configmapnew.yaml
charts/hami/templates/scheduler/deployment.yaml
charts/hami/templates/scheduler/device-configmap.yaml
charts/hami/templates/scheduler/job-patch/clusterrolebinding.yaml
charts/hami/templates/scheduler/job-patch/job-createSecret.yaml
charts/hami/templates/scheduler/job-patch/job-patchWebhook.yaml
charts/hami/templates/scheduler/job-patch/role.yaml
charts/hami/templates/scheduler/job-patch/rolebinding.yaml
charts/hami/templates/scheduler/job-patch/serviceaccount.yaml
charts/hami/templates/scheduler/rolebinding.yaml
charts/hami/templates/scheduler/service.yaml
charts/hami/templates/scheduler/serviceaccount.yaml
charts/hami/templates/scheduler/webhook.yaml
charts/hami/values.yaml

/kind deployment
Add namespace override for multi-namespace deployments in combined charts.
refer: https://github.com/NVIDIA/dcgm-exporter/pull/65

chore: add namespace override for multi-namespace deployments

---

docker/Dockerfile.withlib

/kind bug
The `harbor.4pd.io/sagegpt-aio/pk_platform/ubuntu:22.04` image cannot be accessed.
```
Dockerfile.withlib:14
--------------------
12 |     
13 |     #FROM ubuntu:24.04
14 | >>> FROM harbor.4pd.io/sagegpt-aio/pk_platform/ubuntu:22.04
15 |     ENV NVIDIA_DISABLE_REQUIRE="true"
16 |     ENV NVIDIA_VISIBLE_DEVICES=all
--------------------
ERROR: failed to solve: harbor.4pd.io/sagegpt-aio/pk_platform/ubuntu:22.04: failed to do request: Head "https://harbor.4pd.io/v2/sagegpt-aio/pk_platform/ubuntu/manifests/22.04": EOF
```
Fixes #

fix ubuntu base image in Dockerfile.withlib

---

README.md
README_cn.md
charts/hami/templates/scheduler/certmanager.yaml
charts/hami/templates/scheduler/job-patch/clusterrole.yaml
charts/hami/templates/scheduler/job-patch/clusterrolebinding.yaml
charts/hami/templates/scheduler/job-patch/job-createSecret.yaml
charts/hami/templates/scheduler/job-patch/job-patchWebhook.yaml
charts/hami/templates/scheduler/job-patch/psp.yaml
charts/hami/templates/scheduler/job-patch/role.yaml
charts/hami/templates/scheduler/job-patch/rolebinding.yaml
charts/hami/templates/scheduler/job-patch/serviceaccount.yaml
charts/hami/templates/scheduler/webhook.yaml
charts/hami/values.yaml
docs/config.md
docs/config_cn.md

/kind feature
cert-manager streamlines and automates TLS certificate management in Kubernetes, enhancing security and reducing operational complexity for webhook authentication.
No.

chore: helm chart support scheduler webhook cert-manager

---

pkg/scheduler/nodes.go
pkg/scheduler/nodes_test.go
pkg/scheduler/pods.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind bug
avoid literal copies lock value from
This pull request simplifies the initialization of `nodeManager` and `podManager` by replacing the `init` methods with constructors. Additionally, it updates the `Scheduler` struct to use pointers for these managers and modifies the related tests accordingly.
Initialization improvements:
* [`pkg/scheduler/nodes.go`](diffhunk://#diff-ceaaf9a9ad22b7be7e62cbb755f901974473813e73b151a996e264c224eb3f42L42-R45): Replaced the `init` method with a `newNodeManager` constructor to initialize the `nodeManager` struct.
* [`pkg/scheduler/pods.go`](diffhunk://#diff-3ec08c427c616f48490edbbb2d26694e5719f799c84ad6b8a25cb77637fe9cdfL50-R55): Replaced the …

refactor(scheduler): replace init methods with constructor functions

---

pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
pkg/device-plugin/nvidiadevice/nvinternal/plugin/util.go

/kind bug
This pull request includes several changes to improve error handling and add additional logging in the Nvidia device plugin. The most important changes involve initializing the NVML library with error checks and modifying the `GetDeviceNums` function to return an error.
Improvements to error handling:
* [`pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go`](diffhunk://#diff-f01e6dee63f1e8bca06b5508aeaee9563a45f2e0c58c8dd4ef917c346f1552c0L113-R116): Added error handling for `nvml.Init()` in the `getAPIDevices` method. If initialization fails, an error is logged and a panic is triggered.
* [`pkg/device-plugin/nvidiadevice/nvinternal/plugin/util.go`](diffhunk://#diff-8b63c6d64d45d3fd4890aafbcf25428f074708 …

fix: Add error handling for nvml.Init in NvidiaDevicePlugin

---

pkg/scheduler/scheduler.go

scheduler: fix duplicate handling of the node label selector

---

.github/workflows/ci.yaml
.golangci.yaml
cmd/vGPUmonitor/testcollector/main.go
hack/tools/preferredimports/preferredimports.go
hack/verify-staticcheck.sh
pkg/device/cambricon/device.go
pkg/device/cambricon/device_test.go
pkg/device/metax/protocol.go
pkg/device/nvidia/device_test.go
pkg/util/nodelock/nodelock.go
test/utils/pod.go

/kind cleanup
This pull request includes several important changes to improve the linting process, update dependencies, and refactor code for better readability and maintainability. Below are the most significant changes:
* Updated the CI workflow to use `golangci-lint-action` version 2.0 for linting instead of running `make lint` directly. (`.github/workflows/ci.yaml`)
* Updated `golangci-lint` to version 2.1.1 in `hack/verify-staticcheck.sh` and changed the installation method to use the latest script from the repository's HEAD. (`hack/verify-staticcheck.sh`) [[1]](diffhunk://#diff-dd4a155c58c25cd819d2b0025bf96bba44cd82f6dc4aad132fa48b7ec9ab3bb7L21-R21) [[2]](diffhunk://#diff-dd4a155c58c25cd819d2b0025bf96bba44cd82f6dc4a …

refactor(.github/workflows/ci.yaml): Update golangci-lint to v2.0 and modify .golangci.yaml

---

pkg/scheduler/nodes.go
pkg/scheduler/nodes_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind bug
This PR mainly fixes the following issues in rmNodeDevice:
1. Incorrectly deleting some devices from the node.
https://github.com/Project-HAMi/HAMi/blob/38bed6fb23cfd913b6ce009ee8f8a79cb014db23/pkg/scheduler/nodes.go#L85-L93
This will cause anything inconsistent with the vendor to be deleted, which doesn't seem to align with the function's purpose. Please let me know if I've misunderstood.
2. Concurrent read/write issues for `nodes`. Although this problem is frequent in the code, this PR fixes the issue in this specific function :smile:
3. The log exists before the `rmNodeDevice` function, so the printed device information is incorrect.
https://github.com/Project-HAMi/HAMi/blob/38bed6fb23cfd913b6ce009ee8f8a79cb0 …

scheduler: fix removing node devices from node manager

---

docs/config.md

Per https://github.com/Project-HAMi/HAMi/issues/372 and https://github.com/Project-HAMi/HAMi/issues/1003, ACTIVE_OOM_KILLER is deprecated and needs to be removed from the documentation.
Fixes #372

docs: Remove ACTIVE_OOM_KILLER environment variable description

---

cmd/scheduler/main.go
cmd/vGPUmonitor/main.go

/kind cleanup
This pull request includes important changes to the `cmd/vGPUmonitor/main.go` file to improve error handling by modifying functions to return errors instead of terminating the program.
Error handling improvements:
* Changed the `Run` function in the `rootCmd` to `RunE` to handle errors and return them instead of calling `start()` directly. (`[cmd/vGPUmonitor/main.goL45-R47](diffhunk://#diff-093602e3776eeab4544178697b6844906795d96cfede8a687dc0bd52062cd4a7L45-R47)`)
* Modified the `start` function to return an error instead of terminating the program with `klog.Fatalf` when encountering validation or creation errors. (`[cmd/vGPUmonitor/main.goL58-R65](diffhunk://#diff-093602e3776eeab4544178697b6844906795d96cfe …

refactor(vGPUmonitor): change Run to RunE and return errors

---

charts/hami/templates/device-plugin/runtime-class.yaml
charts/hami/templates/scheduler/device-configmap.yaml
charts/hami/values.yaml
pkg/device/nvidia/device.go
pkg/scheduler/webhook.go

/kind feature
1. helm `values.yaml` adds the `devicePlugin.createRuntimeClass` parameter, which allows you to choose whether or not to create the corresponding `RuntimeClass` resource if the user sets the parameter `devicePlugin.runtimeClassName`.
2. After the hami-schedule webhook determines that the pod is using nvidia resources, it will set the `pod.Spec.RuntimeClassName` according to the `runtimeClassName` parameter if the user has not set it.
Benefits:
- Using RuntimeClass is more convenient and flexible than setting up a default container runtime.
- In the cri runtime environment, it is no longer necessary to set the default container runtime.
Ref: https://github.com/NVIDIA/k8s-device-plugin/blob/main/README.md#inst …

feat: Support for using RuntimeClass with nvidia devices

---

charts/hami/templates/device-plugin/daemonsetnvidia.yaml
charts/hami/templates/scheduler/deployment.yaml

/kind feature
When managing HAMi via helm chart, the `hami-device-plugin` and `hami-scheduler` components should be restarted automatically when updating the `ConfigMap` contents referenced by the `hami-device-plugin` and `hami-scheduler`.
No.

feat: helm chart add checksum annotation for restarting hami component after ConfigMap modification

---

docker/Dockerfile
docker/Dockerfile.hamicore
docker/Dockerfile.hamimaster
docker/Dockerfile.withlib

/kind feature
Fixes # https://github.com/Project-HAMi/HAMi/issues/752
- in `hami-device-plugin` pod
- in host

add nvidia-smi command show cuda version info

---

docs/proposals/gpu-topo-policy.md
pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
pkg/device/nvidia/calculate_score.go
pkg/device/nvidia/calculate_score_test.go
pkg/device/nvidia/device.go
pkg/device/nvidia/links.go
pkg/util/util.go

Fixes https://github.com/Project-HAMi/HAMi/issues/822

Add nvidia gpu topoloy score registry to node

---

.github/labeler.yml
.github/workflows/auto-label-pr.yaml

/kind feature
This PR add an action in workflow that when a pull request is created, this action will help labeling this pull request automatically based on the rules in `.github/labeler.yml`
Fixes #
There are some test results in my [repo](https://github.com/Shouren/test-labeler)

feat(Actions): Add an action to label pr automatically

---

README.md
README_cn.md
charts/hami/Chart.yaml

/kind bug
This PR fixes Helm installation failure on GKE clusters where Kubernetes versions include a pre-release suffix (e.g., `v1.32.3-gke.1785003`). Helm uses [Masterminds/semver](https://github.com/Masterminds/semver), which by spec skips pre-releases when comparing against a constraint like `>= 1.18.0`.
From the semver spec used by Helm:
> “>=1.2.3 will skip pre-releases when looking at a list of releases, while >=1.2.3-0 will evaluate and find pre-releases.”
> 
Therefore, changing the constraint to `>= 1.18.0-0` ensures compatibility with Kubernetes versions that use pre-release identifiers, including those from GKE and other distributions.
Additionally, this PR updates the minimum supported Kubernetes version in …

fix(chart): support GKE pre-release versions via kubeVersion '-0'

---

cmd/scheduler/main.go
pkg/scheduler/config/config.go
pkg/util/nodelock/nodelock.go
pkg/util/nodelock/nodelock_test.go

This PR makes the HAMi scheduler's node lock timeout configurable, allowing operators to adjust the timeout duration based on their cluster characteristics and scheduling requirements.
1. __Configuration Layer (`pkg/scheduler/config/config.go`)__
- Added `NodeLockTimeout int` configuration parameter
- Default value set to 1 minute to maintain backward compatibility
2. __Command Line Interface (`cmd/scheduler/main.go`)__
- Added `--node-lock-timeout` flag to scheduler command line options
- Flag accepts timeout value in minutes
- Integrated timeout initialization in the `start()` function
3. __Runtime Behavior (`pkg/util/nodelock/nodelock.go`)__
- The global `NodeLockTimeout` variable is now set from configuration
- Maintains existing lock/unlock logic and timeout checking mechanism …

feat(scheduler): make node lock timeout configurable

---

charts/hami/templates/scheduler/deployment.yaml
charts/hami/values.yaml
cmd/scheduler/main.go
pkg/scheduler/config/config.go
pkg/scheduler/webhook.go
pkg/scheduler/webhook_test.go

According to the [code](https://github.com/kubernetes/kubernetes/blob/87562da40ac762ad62476d6f8d0f466e9825985c/pkg/apis/core/v1/defaults.go#L214), the Kubernetes API Server will set the `schedulerName` in PodSpec to default value if not set. 
This PR introduce a switch named `forceOverwriteDefaultScheduler` to fix #1162,
Fixes #
@archlitchi 

fix: Add option for overwrite schedulerName

---

docker/Dockerfile
docs/how-to-profiling-scheduler.md
docs/how-to-profiling-scheduler_cn.md
hack/build.sh
version.mk

To fix compile error with #1171 
```bash
5.989 go: downloading sigs.k8s.io/randfill v1.0.0
6.018 go: downloading github.com/emicklei/go-restful/v3 v3.11.3
6.022 go: downloading github.com/go-openapi/jsonpointer v0.21.0
6.025 go: downloading github.com/mailru/easyjson v0.7.7
6.066 go: downloading github.com/josharian/intern v1.0.0
6.093 go: sigs.k8s.io/controller-runtime@v0.21.0 requires go >= 1.24.0 (running go 1.22.5; GOTOOLCHAIN=local)
6.099 make: *** [Makefile:37: scheduler] Error 1
```
Fixes #
@archlitchi @wawa0210 

build(deps): upgrade golang to 1.24.4

---

cmd/scheduler/metrics.go

/kind design
The metric vGPUPodsDeviceAllocated docs at https://project-hami.io/zh/docs/userguide/monitoring/device-allocation/ 
is using label to expose core allocation. But it is not a standard usage of metric and not friendly for dashboard like Grafana to display.
This pr removes and replaces it with two metrics that already exist.
This pr change the metrics name and value. But we can discuss how to migrate more user-friendly.

remove redundant metrics for vgpu allocation

---

pkg/scheduler/webhook.go

/kind bug
This PR updates the `Handle()` func in `pkg/scheduler/webhook.go`. The previous implementation using `req.UID` and `req.Name` when logging. However, according to the doc of [AdmissionRequest](https://pkg.go.dev/k8s.io/api/admission/v1#AdmissionRequest) as below:
> // UID is an identifier for the individual request/response. It allows us to distinguish instances of requests which are
// otherwise identical (parallel requests, requests when earlier requests did not modify etc)
// The UID is meant to track the round trip (request/response) between the KAS and the WebHook, not the user request.
// It is suitable for correlating log entries between the webhook and apiserver, for either auditing or debugging.
UID …

fix: wrong Pod's UID and emtpy Pod's name in log of webhook.go

---

charts/hami/templates/scheduler/clusterrole.yaml
pkg/util/nodelock/nodelock.go

/kind feature
Use clientset Patch instead of Update in `pkg/util/nodelock`.
Fixes #1156 
None.
None.

perf(util/nodelock): Use clientset Patch instead of Update.

---

pkg/device-plugin/nvidiadevice/nvinternal/plugin/util.go
pkg/device-plugin/nvidiadevice/nvinternal/rm/health.go
pkg/device/enflame/device.go
pkg/device/hygon/device.go
pkg/device/kunlun/device.go
pkg/scheduler/score_test.go
pkg/util/util.go

The `SplitSeq` method is introduced in strings package since Go 1.24.0, and ranging over `SplitSeq` is more efficient
Fixes #

refactor: Ranging over SplitSeq is more efficient

---

docs/ascend910b-support.md
docs/ascend910b-support_cn.md

`Ascend docker runtime` project has been migrated to GitCode [`Ascend/mind-cluster`](https://gitcode.com/Ascend/mind-cluster), so the link for `Ascend docker runtime` need to be updated.

docs: update ascend910b-support docs

---

charts/hami/templates/scheduler/clusterrole.yaml
cmd/scheduler/metrics.go
pkg/device/ascend/device.go
pkg/device/awsneuron/device.go
pkg/device/cambricon/device.go
pkg/device/common/common.go
pkg/device/devices.go
pkg/device/enflame/device.go
pkg/device/enflame/device_test.go
pkg/device/enflame/gcu.go
pkg/device/hygon/device.go
pkg/device/iluvatar/device.go
pkg/device/kunlun/device.go
pkg/device/kunlun/vdevice.go
pkg/device/metax/device.go
pkg/device/metax/sdevice.go
pkg/device/mthreads/device.go
pkg/device/nvidia/device.go
pkg/device/quota.go
pkg/device/quota_test.go
pkg/scheduler/config/config.go
pkg/scheduler/config/config_test.go
pkg/scheduler/pods.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/util/util.go

/kind feature
This pr add resource quota support for Nvidia multi-device request and whole device request.
Fixes #

feat: add NVIDIA Resourcequota
