- README.md
- README_cn.md
- docs/dashboard.md
- docs/dashboard_cn.md
- docs/gpu-dashboard.json
> feature: add grafana dashboard example

- docs/gpu-dashboard.json
fix: #106 
gpu下拉框 与 node 下拉框进行联动
> fix: dashboard list gpu bug

- pkg/scheduler/scheduler.go
- "found" 这个 flag 只在外层 for 循环的外面初始化为 false。导致内层的 for 循环将 "found" 置为 true 之后，数组后面的 devices 再判断 "found" 时都为 true，代码 `nodeInfo.Devices = append(nodeInfo.Devices, ` 都不会执行。也就是说，新增的devices无法被添加到scheduler的可调度数组当中。
- 使用 nodeLister 从本地缓存list所有nodes, 替换每次都使用kubeClient从apiserver去list，加快运行速度。
> bugfix: unable to dynamically add node's devices

- pkg/util/util.go
Fixes: https://github.com/4paradigm/k8s-vgpu-scheduler/issues/116
> fix device-plugin panic

- .gitignore
- go.sum
After using go mod vendor and go mod tidy, I found that the go.sum file has changed.
```
go version go1.21.0 darwin/arm64
```
> Fix go.sum file

- cmd/device-plugin/nvidia/main.go
- cmd/device-plugin/nvidia/vgpucfg.go
- cmd/scheduler/metrics.go
- cmd/vGPUmonitor/feedback.go
- cmd/vGPUmonitor/metrics.go
- cmd/vGPUmonitor/pathmonitor.go
- pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
- pkg/scheduler/pods.go
- pkg/util/util.go
- To improve the readability and maintainability of the log.
- To improve performance.
- The log messages are now more concise and readable.
- The code is now cleaner.
The changes were tested and passed.
```
~/code/k8s-vgpu-scheduler% make all
go build -ldflags '-s -w -X 4pd.io/k8s-vgpu/pkg/version.version=unknown' -o bin/scheduler ./cmd/scheduler
go build -ldflags '-s -w -X 4pd.io/k8s-vgpu/pkg/version.version=unknown' -o bin/vGPUmonitor ./cmd/vGPUmonitor
go build -ldflags '-s -w -X 4pd.io/k8s-vgpu/pkg/version.version=unknown' -o bin/mlu-device-plugin ./cmd/device-plugin/mlu
go build -ldflags '-s -w -X 4pd.io/k8s-vgpu/pkg/version.version=unknown' -o bin/nvidia-device-plugin ./cmd/device-plugin/nvidia
```
> Improved log messages

- charts/vgpu/templates/device-plugin/daemonsetnvidia.yaml
This pull request removes the duplicated key command from the following files:
charts/vgpu/templates/device-plugin/daemonsetnvidia.yaml
> :wrench:Remove  duplicated key 'command'

- Makefile
- charts/vgpu/templates/device-plugin/daemonsetnvidia.yaml
- charts/vgpu/values.yaml
- cmd/vGPUmonitor/main.go
- cmd/vGPUmonitor/metrics.go
- cmd/vGPUmonitor/pathmonitor.go
- cmd/vGPUmonitor/pathmonitor_test.go
- cmd/vGPUmonitor/validation.go
- docker/Dockerfile
- docker/entrypoint.sh
- pkg/device-plugin/nvidiadevice/nvinternal/plugin/register_test.go
- pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
- pkg/device-plugin/nvidiadevice/nvinternal/plugin/server_test.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/health_test.go
- pkg/scheduler/pods.go
- version.mk
- Added a version.mk file to maintain version information.
- Improved test coverage by adding unit tests for various functions.
- Enhanced the clarity and usefulness of the log messages.
- Optimized the UT function via GPT-4
> :zap: add version.mk and UTs for some functions

- .github/workflows/ci.yaml
Fixes: https://github.com/Project-HAMi/HAMi/issues/149
> add a ci job to build dev image

- cmd/device-plugin/nvidia/vgpucfg.go
- cmd/vGPUmonitor/feedback.go
- cmd/vGPUmonitor/pathmonitor.go
- pkg/device-plugin/hygon/dcu/amdgpu/amdgpu.go
- pkg/device-plugin/hygon/dcu/server.go
- pkg/device-plugin/mlu/cndev/cndev.go
- pkg/device-plugin/mlu/cntopo/cntopo.go
Part of #https://github.com/Project-HAMi/HAMi/pull/135
> cleanup: remove io/ioutil package

- pkg/scheduler/nodes.go
- pkg/scheduler/pods.go
- pkg/scheduler/score.go
reduce race condition. replace mutex to RWmutex
> reduce race condition. replace mutex to RWmutex

- .github/workflows/ci.yaml
Fixes: https://github.com/Project-HAMi/HAMi/issues/155
> add repo-token to fix protoc api rate limit

- charts/hami/templates/scheduler/configmapnew.yaml
Fixes: https://github.com/Project-HAMi/HAMi/issues/89
> upgrade kubescheduler version

- README.md
- README_cn.md
- docs/cambricon-mlu-support.md
- docs/cambricon-mlu-support_cn.md
- docs/hygon-dcu-support.md
- docs/hygon-dcu-support_cn.md
Fixes: https://github.com/Project-HAMi/HAMi/issues/153
> fix README.md link address

- docs/develop/protocol.md
- pkg/device/iluvatar/device.go
- pkg/device/nvidia/device.go
- pkg/util/util_test.go
fix: https://github.com/Project-HAMi/HAMi/issues/177
use `hami.io` to replace `hami.sh`.
> replace hami.sh to hami.io

- cmd/device-plugin/nvidia/main.go
- cmd/scheduler/metrics.go
- cmd/vGPUmonitor/metrics.go
- pkg/device-plugin/hygon/dcu/register.go
- pkg/device-plugin/mlu/register.go
- pkg/device-plugin/mlu/server.go
- pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
- pkg/device/cambricon/device.go
- pkg/device/hygon/device.go
- pkg/device/iluvatar/device.go
- pkg/scheduler/routes/route.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/score.go
Fixes: https://github.com/Project-HAMi/HAMi/issues/213
> fix klog upgrade after verify error

- .github/workflows/ci.yaml
- .github/workflows/dev-image-build.yaml
- Makefile
- hack/kubeconfig-demo.yaml
- hack/unit-test.sh
> add ut action

- pkg/scheduler/webhook.go
Fixes: https://github.com/Project-HAMi/HAMi/issues/209
> fix: init controller-runtime log.SetLogger()

- pkg/device/devices.go
Fixes: https://github.com/Project-HAMi/HAMi/issues/206
> fix devices registry name error for Cambricon and Hygon this two type

- README.md
- example.yaml
- examples/nvidia/mig_example.yaml
Delete useless symbols and fix descriptive errors in yaml examples.
> Delete useless symbols and fix descriptive errors in yaml examples.

- .github/PULL_REQUEST_TEMPLATE.md
- .github/issue_template.md
At present, the warehouse does not have a more standard pr and issue templates, I have added a preliminary version
> feat: add github issue and pr templete

- .github/workflows/robot.yaml
add a robot to mark labels
fixed: https://github.com/Project-HAMi/HAMi/issues/204
> add a robot to mark labels

- pkg/device/nvidia/device_test.go
/kind bug
Many PR pipeline errors are reported due to lint
such as
1. https://github.com/Project-HAMi/HAMi/actions/runs/8527140422/job/23357898905?pr=240
Fixes #
> fix make lint error

- README.md
- README_cn.md
> add cncf landscape logo

- README.md
- README_cn.md
> update slack url

- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
- README_cn.md
preview --> https://github.com/wawa0210/HAMi/tree/master
Fixes #
> add contributing guideline and update contact

- AUTHORS
- MAINTAINERS.md
- README.md
- docs/develop/CONTRIBUTOR-LADDER.md
> add contributer ladder docs

- docs/develop/design.md
修正文档中的错误描述
Fixes #
- 修正了设计文档中有关海光设备拦截库名称的错误描述
无
无
> doc: modify docs/develop/design.md the error .so file description of the iluvatar device

- examples/nvidia/specify_card_type_to_use.yaml
> trivy:fix specify card type to use error

- README.md
- README_cn.md
> fix bad link in README

- cmd/vGPUmonitor/cudevshr.go
- cmd/vGPUmonitor/metrics.go
/kind feature
Part of https://github.com/Project-HAMi/HAMi/pull/258
> Support GPU Utilization Metrics

- pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
/kind cleanup
Current the loop interval is 30s,but the log show is 30ns
```bash
I0428 06:02:25.001360 1438494 register.go:197] Successfully registered annotation. Next check in 30ns seconds...
I0428 06:02:55.154692 1438494 register.go:197] Successfully registered annotation. Next check in 30ns seconds...
I0428 06:03:25.269872 1438494 register.go:197] Successfully registered annotation. Next check in 30ns seconds...
I0428 06:03:55.362878 1438494 register.go:197] Successfully registered annotation. Next check in 30ns seconds...
I0428 06:04:25.583680 1438494 register.go:197] Successfully registered annotation. Next check in 30ns seconds...
I0428 06:04:55.695531 1438494 register.go:197] Successfully registered annotation. Next check in 30ns seconds...
I0428 …
```
> fix RegistrInAnnotation log time error

- README.md
- README_cn.md
> add break change document

- OWNERS
About the difference between reviewer and approver
reviewers: can be responsible for reviewing the code. If the code is ok, it can be marked `/lgtm`
approver: can type `/lgtm` and `/approve`
A pr merge requires at least 1 lgtm and 1 approve (configurable).
Fixes #
> add hami repos owners to triger hami pipeine robot

- charts/hami/templates/scheduler/deployment.yaml
- charts/hami/values.yaml
/kind feature
Add scheduling startup parameters
Fixes #
> add scheduler command

- README.md
- README_cn.md
- docs/config.md
- docs/config_cn.md
- examples/nvidia/specify_scheduling_policy.yaml
add scheduler policy doc
Fixes #
> add scheduler policy doc

- charts/hami/templates/scheduler/job-patch/job-patchWebhook.yaml
Do not use job-patch to modify failurePolicy
https://github.com/Project-HAMi/HAMi/blob/master/charts/hami/values.yaml#L96-L97
Currently, we can customize the failurePolicy.
Fixes #
> Do not use job-patch to modify failurePolicy.

- README.md
- README_cn.md
> update hami roadmp

- pkg/scheduler/scheduler.go
/kind cleanup
If the node is not registered with HAMi, the log output is confusing, so increase the log output level and optimize the content
Fixes #308
> enhance unregisterd node logs

- README.md
- README_cn.md
Fixes # https://github.com/Project-HAMi/HAMi/issues/330
> fix README.md doc

- examples/nvidia/use_as_normal.yaml
- examples/nvidia/use_exclusive_card.yaml
- pkg/scheduler/scheduler.go
> fix: typo in use_exclusive_card.yaml and add new exclusive example

- go.mod
- go.sum
Fixes # https://github.com/Project-HAMi/HAMi/issues/370
> upgrade go-nvml version

- README_cn.md
① Add the corresponding markdown flag to the command 
② Fix using Hami to schedule GPU case yaml indentation
Fixes #
> docs: Optimize the user experience of using documents

- .github/workflows/dev-image-build.yaml
- charts/hami/templates/scheduler/configmap.yaml
- charts/hami/templates/scheduler/configmapnew.yaml
- charts/hami/templates/scheduler/deployment.yaml
- charts/hami/values.yaml
- pkg/device/ascend/ascend310p.go
- pkg/device/devices.go
/kind feature
Add support for Huawei Ascend 310p.
Fixes #
> feat: support huawei ascend310p

- pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
> fix: CUDA_DISABLE_CONTROL not working properly

- .github/workflows/build-helm-release.yaml
- .github/workflows/build-image-release.yaml
- .github/workflows/lint-chart.yaml
- .github/workflows/main.yml
- charts/hami/Chart.yaml
- docs/CHANGELOG/CHANGELOG-0.0.0.md
- docs/release-process.md
- hack/util.sh
- hack/verify-chart-version.sh
/kind feature
Fixes #
* build hami mutil arch image when create a tag.
* release chart tag in branch gh-page when change the chart version
* add ci to verify wherher appVersion and version are the same
> add workflow to build chart tag and image

- version.mk
/kind cleanup
``` shell
make docker
```
Fixes #
> fixed go build image version

- README.md
> add hami community Governance

- .github/workflows/dev-image-build.yaml
> add image vulnerability scanner

- .github/workflows/ci-image-scanning.yaml
- .github/workflows/dev-image-build.yaml
> add hami vulnerability scan and report

- pkg/scheduler/pods.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
Fixes # https://github.com/Project-HAMi/HAMi/issues/418
> fix data race when read pods info

- .github/workflows/codeql-analysis.yml
> add CodeQL analysis

- pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
- pkg/device/nvidia/device.go
- pkg/util/nodelock/nodelock.go
- pkg/util/util.go
Add `hami.io/bind-pod-info` annotation, to record current `allocate` device pod.
Fixes # https://github.com/Project-HAMi/HAMi/issues/404
> add node record pod info

- README.md
- README_cn.md
as https://github.com/cncf/toc/issues/1413
Fixes #
> update hami sandbox project

- README.md
- README_cn.md
> Add OpenSSF Best Practices Badge

- .github/workflows/ci-image-scanning.yaml
- .github/workflows/ci.yaml
- Makefile
- hack/unit-test.sh
as https://github.com/cncf/toc/issues/1413
/kind feature
Fixes #
> support code  Coverage Analytics

- .github/workflows/build-image-release.yaml
- pkg/scheduler/score.go
1. 'main' -> 'master' in CI (we don't have a main branch)
2. fix golang-lint check error
> fix CI and go-lint check error

- charts/hami/templates/scheduler/deployment.yaml
/kind bug
fix device configmap name
Fixes #
> fix device configmap

- .github/workflows/lint-chart.yaml
> fix chart lint always running when charts has no change

- .github/workflows/ci.yaml
> support pr commit can also build images

- .github/workflows/ci.yaml
/kind bug
Currently, we only build images during the CI process to ensure that the code is correct, but we do not push images.
Due to security policy, pr process secrets cannot be read
https://github.com/orgs/community/discussions/25196
Fixes #
> build test for  pr image

- .github/workflows/ci-image-scanning.yaml
/kind bug
Trivy scan failed due to insufficient disk space
https://github.com/Project-HAMi/HAMi/actions/runs/10985643008/job/30497816583
https://github.com/Project-HAMi/HAMi/actions/runs/11004645589/job/30557541606
Fixes #
> fix trivy scan failed because low disk

- .github/workflows/ci-image-scanning.yaml
/kind bug
Lack of golang basic environment causes build compilation errors
https://github.com/Project-HAMi/HAMi/actions/runs/11079447020/job/30788510535
Fixes #
> fix trivy scan

- README.md
> fix build badge status

- .github/release.yml
> update action-gh-release template file to more accurate matching

- charts/hami/templates/scheduler/job-patch/job-createSecret.yaml
- charts/hami/templates/scheduler/webhook.yaml
- charts/hami/values.yaml
/kind feature
Refactor `.Values.scheduler.customWebhook` block, adding support for defining webhook's `reinvocationPolicy` and resolving misleading structure.
Resolves: #531
Default behaviour stays the same so there are no breaking changes in that aspect.
Users should upgrade their `values.yaml` files as there are structural changes which introduce breaking changes.
> Refactor helm "Admission Webhook" config.

- README.md
- README_cn.md
- charts/hami/templates/scheduler/configmap.yaml
- charts/hami/templates/scheduler/configmapnew.yaml
- charts/hami/values.yaml
- docs/mthreads-support.md
- docs/mthreads-support_cn.md
- examples/mthreads/default_use.yaml
- examples/mthreads/multi_cards.yaml
- examples/mthreads/use_exclusive.yaml
- pkg/device/ascend/device.go
- pkg/device/cambricon/device.go
- pkg/device/devices.go
- pkg/device/hygon/device.go
- pkg/device/iluvatar/device.go
- pkg/device/mthreads/device.go
- pkg/device/nvidia/device.go
- pkg/device/nvidia/device_test.go
- pkg/scheduler/score.go
- pkg/scheduler/webhook.go
Support mthreads GPU slicing, for more details, see docs/mthreads-support.md
> Mthreads support

- pkg/util/util.go
/kind bug
Fix code scanning alert-Incorrect conversion between integer types
Fixes #549 
Fixes #548 
Fixes #547
> Fix code scanning alert-Incorrect conversion between integer types

- README.md
- README_cn.md
> migrate hami slack to cncf hami group

- pkg/k8sutil/pod_test.go
/kind test
ref https://github.com/Project-HAMi/HAMi/issues/569
Fixes #
> improve pkg/k8sutil/pod.go ut coverage

- README.md
- README_cn.md
Add WebUI to readme and readme_cn.md
> Add WebUI to readme and readme_cn.md

- README.md
- README_cn.md
> update HAMi Talks and References

- pkg/scheduler/score.go
- pkg/scheduler/score_test.go
/kind bug
fix wrong quota for fitInDevices
Fixes #592
> fix: wrong quota for fitInDevices

- pkg/scheduler/policy/gpu_policy_test.go
- pkg/scheduler/policy/node_policy_test.go
What type of PR is this?
/kind test
ref #569
Fixes #
> add ut about schedule policy

- examples/nvidia/specify_uuid_to_use.yaml
When a specific physical GPU device is assigned, the container can only request one GPU.
Help the user feel less confused.
Personal observation, No issues found.
**Does this PR introduce a user-facing change?**: no
> fix-example-yaml 

- pkg/device/ascend/device_test.go
/kind test
add ut for device/ascend
> add ut for ascend

- cmd/vGPUmonitor/metrics.go
- pkg/monitor/nvidia/cudevshr.go
Fix https://github.com/Project-HAMi/HAMi/pull/683 this pr introduced code format issues.
Fixes #
> fix code lint faild

- pkg/scheduler/event_test.go
/kind test
add ut for pkg/scheduler/event.go
> add ut for pkg/scheduler/event.go

- pkg/scheduler/nodes_test.go
/kind test
add ut for scheduler/nodes
> add ut for nodes

- pkg/scheduler/event_test.go
/kind cleanup
add license for pkg/scheduler/event_test.go
Fixes # https://github.com/Project-HAMi/HAMi/pull/688
> add license for pkg/scheduler/event_test.go

- pkg/device/nvidia/device_test.go
/kind test
add ut for device/nvidia InitNvidiaDevice/PatchAnnotations/GetNodeDevices func
> add ut for device/nvidia

- pkg/monitor/nvidia/v0/spec_test.go
What type of PR is this?
/kind test
What this PR does / why we need it:
add ut for pkg/monitor/nvidia/v0/spec.go func
Which issue(s) this PR fixes:
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
> add ut for pkg/monitor/nvidia/v0/spec.go

- pkg/device/cambricon/device.go
- pkg/device/cambricon/device_test.go
/kind bug
1、fix When i is 0, it will cause the following error
`panic: invalid argument to Intn [recovered]
panic: invalid argument to Intn
`
2、add ut for the device/cambricon（setNodeLock、LockNode、ReleaseNodeLock）
> random time may be zero

- pkg/scheduler/pod_test.go
What type of PR is this?
/kind test
What this PR does / why we need it:
add ut for /pkg/scheduler/pod.go func
Which issue(s) this PR fixes:
Fixes # #569
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
> add ut for github.com/Project-HAMi/HAMi/pkg/scheduler/pod.go

- pkg/util/nodelock/nodelock_test.go
/kind test
add ut for  pkg/util/nodelock/nodelock.go
Fixes  # https://github.com/Project-HAMi/HAMi/issues/569
> add ut for  pkg/util/nodelock/nodelock.go

- pkg/version/version_test.go
/kind test
add ut for pkg/version/version.go
> test: add ut for pkg/version/version.go

- Makefile
> fix device-plugin-version

- docs/config.md
- docs/config_cn.md
Only updated the markdown format and layout.
> [Docs] update config pages

- pkg/device-plugin/nvidiadevice/nvinternal/rm/device_map_test.go
> add ut for device-map

- pkg/device-plugin/nvidiadevice/nvinternal/rm/nvml_devices_test.go
> add ut nvml devices

- pkg/device/ascend/device_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/util/util.go
- pkg/util/util_test.go
/kind flake
Use the built-in DateTime to format time
Fixes #
> Optimize the time format layout

- .github/workflows/auto-release.yaml
- .github/workflows/call-e2e.yaml
- .github/workflows/ci.yaml
- Makefile
- Makefile.defs
- charts/Makefile
- go.mod
- go.sum
- hack/deploy-helm.sh
- hack/e2e-test-setup.sh
- hack/e2e-test.sh
- hack/util.sh
- test/e2e/node/test_node.go
- test/e2e/node/test_suite_test.go
- test/e2e/pod/test_pod.go
- test/e2e/pod/test_suite_test.go
- test/e2e/test_suite_test.go
- test/utils/common.go
- test/utils/config.go
- test/utils/event.go
- test/utils/node.go
- test/utils/pod.go
/kind feature
Implement initial E2E test suite setup
Fixes #476
Workflow: Build image and Helm chart, upload them to artifacts, run e2e by downloading artifacts
> HAMi supports e2e

- pkg/device/iluvatar/device_test.go
/kind test
add ut for device/iluvatar
> add ut for device/iluvatar

- pkg/device/hygon/device_test.go
/kind test
add ut for device/hygon
> add ut for device/hygon

- pkg/monitor/nvidia/v1/spec_test.go
/kind test
add ut for pkg/monitor/nvidia/v1
> add ut for pkg/monitor/nvidia/v1

- hack/deploy-helm.sh
- hack/util.sh
- test/e2e/pod/test_pod.go
> Enrich pod health check

- README.md
- README_cn.md
fix broken link in readme.md
Fixes #
> docs: fix broken link

- .github/workflows/ci.yaml
- docs/config.md
- hack/util.sh
/kind feature
Optimize E2E execution logic by determining whether file changes
Ignore the files changed under docs, examples and md files
Fixes #
No change:
> Optimize the E2E execution logic

- hack/deploy-helm.sh
- hack/util.sh
- pkg/util/client/client.go
- test/e2e/node/test_node.go
- test/e2e/pod/test_pod.go
- test/e2e/test_suite_test.go
- test/utils/common.go
- test/utils/pod.go
/kind bug
This pull request includes extensive changes to improve the deployment scripts, utility functions, and E2E test cases for the HAMi project. The most important changes include enhancements to the `deploy-helm.sh` script, refactoring of utility functions, and improvements to the E2E test cases for nodes and pods.
* [`hack/deploy-helm.sh`](diffhunk://#diff-090f9afa7f50713325a4a87b521231ea90cfd3d653a377cae98c6d716d293698L16-R22): Improved comments for better readability, added error handling for Helm repository operations, and enhanced Helm chart source validation. [[1]](diffhunk://#diff-090f9afa7f50713325a4a87b521231ea90cfd3d653a377cae98c6d716d293698L16-R22) …
> fix: handle the node nil issue & E2E test failure

- pkg/device/mthreads/device_test.go
/kind test
add ut for device/mthreads
> add ut for device/mthreads

- charts/hami/templates/scheduler/device-configmap.yaml
/kind flake
resolve Configmap formatting issue 
before
after
Fixes #
> fix: Resolve formatting issue in ConfigMap causing display anomalies

- docs/ascend910b-support.md
- docs/ascend910b-support_cn.md
Have a try to improve the text.
/kind cleanup
> [docs] Update ascend910b-support.md

- cmd/scheduler/metrics.go
- pkg/scheduler/pods.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/util/client/client.go
- pkg/util/client/client_test.go
- pkg/util/client/testdata/invalid_kubeconfig.yaml
- pkg/util/client/testdata/kubeconfig.yaml
- pkg/util/util.go
/kind design
This pull request includes several changes aimed at improving logging, refactoring code for better readability, and enhancing test coverage. The most important changes include updating logging statements to use structured logging, refactoring code for clarity, and adding new test cases.
* [`cmd/scheduler/metrics.go`](diffhunk://#diff-927733f66084812250988b65c8c5f8646475f4b26dfbbb1f1ff0f1598976acf0L192-R202): Updated logging statements to use `klog.InfoS` for structured logging and added more detailed log messages for better traceability. [[1]](diffhunk://#diff-927733f66084812250988b65c8c5f8646475f4b26dfbbb1f1ff0f1598976acf0L192-R202) [[2]](diffhunk://#diff-927733f66084812250988b65c8c5f8646475f4b26dfbbb1f1ff0f …
> Refine metrics logs

- charts/hami/templates/scheduler/device-configmap.yaml
- charts/hami/values.yaml
- docs/ascend910b-support.md
- docs/ascend910b-support_cn.md
- pkg/device/devices.go
- pkg/device/devices_test.go
/kind feature
Add 910B4 config to device-configmap for ascend
Fixes #
> Add 910B4 config to device-configmap for ascend

- pkg/scheduler/score_test.go
/kind test
add ut for scheduler/score
> add ut for scheduler/score

- charts/hami/templates/scheduler/device-configmap.yaml
- charts/hami/values.yaml
- pkg/device/devices.go
- pkg/device/devices_test.go
/kind feature
support ascend 910B2
Fixes #
> support ascend 910B2

- docs/benchmark.md
- docs/dashboard.md
- docs/dashboard_cn.md
> fix docs typos

- pkg/scheduler/score.go
/kind feature
Accelerate node score calculations using multiple goroutines
Fixes #
> Accelerate node score calculations using multiple goroutines

- README.md
- docs/cambricon-mlu-support.md
- docs/cambricon-mlu-support_cn.md
- docs/hygon-dcu-support.md
- docs/hygon-dcu-support_cn.md
- docs/iluvatar-gpu-support.md
- docs/iluvatar-gpu-support_cn.md
- docs/mthreads-support.md
- docs/mthreads-support_cn.md
/kind documentation 
- some code blocks had syntax highlighting, while others were missing it
- it's particularly helpful for blocks of YAML and some large blocks of shell
- so added it to those specifically (and I left most one-liner shell blocks as-is without changes)
- also fix some trailing whitespace here and there
n/a
none
no source code changes. improves readability of documentation
> docs: add syntax highlighting to various code blocks

- AUTHORS.md
- MAINTAINERS.md
- Update the MAINTAINERS file with current contributor information
Fixes #
> docs: Update MAINTAINERS file with current contributor information

- OWNERS
Fixes #https://github.com/Project-HAMi/community/issues/16
As one of the earliest members of HAMi, I have contributed more than 30 PRs during this period and have also reviewed a large number of PRs from other contributors.
I believe that becoming a reviewer has enabled me to better assist other contributors in the community.
> Nominate chaunceyjiang to reviewer

- OWNERS
Fixes https://github.com/Project-HAMi/community/issues/15
> add lengrongfu to reviewers

- pkg/device/cambricon/device.go
- pkg/device/cambricon/device_test.go
- pkg/scheduler/pods.go
- pkg/scheduler/scheduler.go
/kind bug
Fixes # https://github.com/Project-HAMi/HAMi/issues/946
> Fix cambricon pods not been recognized by HAMi scheduler

- pkg/device/hygon/device.go
- pkg/device/hygon/device_test.go
/kind bug
bind wrong dcu vdev when concurrent creation
Fixes #920 
> fix: hygon dcu concurrent creation conflict

- DEPENDENCY.md
- SECURITY.md
for https://clomonitor.io/projects/cncf/hami, Dependencies and Security policy
nope
i suggest that we should at least maintain two release versions.
nope
> add Dependencies policy and Security policy

- pkg/scheduler/scheduler.go
/kind bug
There's no need to block the informer process when a new node event comes in, we just need to make sure there's a item in the nodeNotify
Fixes #
> scheduler: fix blocked the nodeNotify channel when node changes

- docs/ascend910b-support.md
- docs/ascend910b-support_cn.md
- examples/ascend/job-310P.yaml
- examples/ascend/job-910A.yaml
- examples/ascend/job-910B2.yaml
- examples/ascend/job-910B3.yaml
- examples/ascend/job-910B4.yaml
Improve the documentation and examples for the Ascend 910 series
None
> docs: Update Ascend910 support documentation

- docs/iluvatar-gpu-support.md
- docs/iluvatar-gpu-support_cn.md
fix errors of the iluvatar's docs
Fixes #
@archlitchi 
nope.
> update iluvatar's docs

- hack/tools/preferredimports/preferredimports.go
- pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/health.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/nvml_manager.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/rm.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/tegra_manager.go
- pkg/device/cambricon/device.go
- pkg/device/devices.go
- pkg/device/devices_test.go
- pkg/device/nvidia/device.go
- pkg/monitor/nvidia/v0/spec_test.go
- pkg/scheduler/scheduler.go
> refactor: replace interface{} with any in various files

- cmd/vGPUmonitor/feedback.go
- cmd/vGPUmonitor/metrics.go
- hack/tools/preferredimports/preferredimports.go
- pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/allocate.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/device_map.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/devices.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/health.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/nvml_manager.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/rm.go
- pkg/device-plugin/nvidiadevice/nvinternal/rm/tegra_manager.go
- pkg/device/ascend/device.go
- pkg/device/cambricon/device.go
- pkg/device/devices.go
- pkg/device/devices_test.go
- pkg/device/hygon/device.go
- pkg/device/iluvatar/device.go
- pkg/device/iluvatar/device_test.go
- pkg/device/metax/sdevice.go
- pkg/device/mthreads/device.go
- pkg/device/nvidia/device.go
- pkg/k8sutil/pod.go
- pkg/monitor/nvidia/v0/spec_test.go
- pkg/scheduler/event_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/score.go
- pkg/scheduler/score_test.go
cleanup
By using modernizer, we can simplify code in this project
Fixes #
> refactor: simplify code by using modern constructs

- cmd/scheduler/main.go
- docs/how-to-profiling-scheduler.md
- docs/how-to-profiling-scheduler_cn.md
feature
This feature helps debugging performance issue and potential memory leaks in HAMi
Fixes #
> feat: Add support for profiling via net/http/pprof package

- docs/scheduler-event-log.md
- pkg/device/nvidia/device.go
- pkg/scheduler/event.go
- pkg/scheduler/event_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/scheduler/score.go
- pkg/scheduler/score_test.go
/kind cleanup
I refactored the filter logs and event messages to enhance their clarity, making it easier for users to troubleshoot issues.
Fixes #
> refactored the filter logs and event messages to enhance their clarity,

- pkg/device/metax/device.go
- pkg/k8sutil/pod.go
/kind bug
fix wrong log and container request device count error
> fix wrong log and container request device count error

- pkg/scheduler/score.go
- pkg/scheduler/score_test.go
> fix vgpu-devices-allocated annotations are inconsistent #991

- docs/develop/roadmap.md
add new ai accelerator GCU S60 made by https://www.enflame-tech.com
as tile, add new ai chip to support in roadmap
Fixes #
we have been working with mengxuan on adding s60 support, and had finished the adaption. thanks. 
No.
> add Enflame GCU S60 into roadmap.

- .github/workflows/ci.yaml
> fix(cicd): update ci.yaml to upload coverage to Codecov

- AUTHORS.md
- MAINTAINERS.md
- charts/hami/Chart.yaml
- docker/Dockerfile
- docker/Dockerfile.withlib
> update maintainer information

- docs/dashboard.md
- docs/dashboard_cn.md
- fix missing apiVersion in serviceMonitor dashboard docs
Fixes #
> fix: missing apiVersion in serviceMonitor dashboard docs

- pkg/util/util_test.go
> test(pkg/util): Add some unit tests for pkg/util

- docs/dynamic-mig-support.md
- docs/dynamic-mig-support_cn.md
add Known Issues for dynamic mig support
Fixes #1120
> documentation: add Known Issues for dynamic mig support

- pkg/device/kunlun/device.go
- pkg/device/kunlun/device_test.go
/kind feature
When the task request 4 cards, some specific cards cross numa can meet it. This pr support this special situation when scheduling inside node.
If possible, the scheduler will leave 2 nodes connected after scheduling for 4 cards task when 6 cards free.
**Does this PR introduce a user-facing change?**: 
No
> Add new kunlun interconnection support

- pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
- pkg/device-plugin/nvidiadevice/nvinternal/plugin/util.go
> featue: mig mode-change #1116

- charts/hami/Chart.yaml
- charts/hami/templates/_commons.tpl
- charts/hami/templates/_helpers.tpl
- charts/hami/templates/device-plugin/daemonsetnvidia.yaml
- charts/hami/templates/scheduler/deployment.yaml
- charts/hami/templates/scheduler/job-patch/job-createSecret.yaml
- charts/hami/templates/scheduler/job-patch/job-patchWebhook.yaml
- charts/hami/values.yaml
/kind feature
add global image for chart
Fixes #
> add global image for chart

- pkg/device/iluvatar/device.go
- pkg/device/iluvatar/device_test.go
> fix: An error occurred while create Iluvatar pod

- .github/release.yml
/kind feature
Since #1053 has been merge, github action will add labels based on the title of a pull request. 
Then we should update the `.github/release.yml` to make those labels works when a new release is made. 
> feat: Add new labels in .github/release.yml

- README.md
- README_cn.md
Current supported device list at README looks like icons instead of buttons. Users can't recognize them as doc references.
> clearly list supported devices doc references at README

- docs/config.md
- docs/config_cn.md
- docs/dynamic-mig-support.md
- docs/dynamic-mig-support_cn.md
Added an example of devicefilter in `dynamic-mig-support`
Fixes #1140 
No
> Add node configs to docs

- .github/workflows/ci.yaml
Fixes #1172
Fixes #
@archlitchi 
> build(deps): Upgrade golang image in ci to 1.24.4

- docker/Dockerfile
This PR helps resolving the security [issues](https://github.com/Project-HAMi/HAMi/security/code-scanning?page=2&query=is%3Aopen+branch%3Amaster+tool%3ATrivy) reported by Trivy image scanning
Fixes #
@archlitchi @wawa0210 
> fix: deal with security issues reported by Trivy in image

- pkg/device/cambricon/device_test.go
Add basic test cases for cambricon module to verify Fit function. Includes positive and negative test scenarios.
Fixes #
no
> Add unit tests for cambricon's Fit Function

- pkg/device/ascend/device_test.go
Add basic test cases for Ascend module to verify Fit function. Includes positive and negative test scenarios.
Fixes #
no
> Add unit tests for Ascend's Fit Function

- pkg/k8sutil/pod.go
bug
修复生成 pod 请求资源时不必要的重复计算
无
辛苦各位审核一下
无
> 修复生成 pod 请求资源时不必要的重复计算

- pkg/util/util.go
bug
修复更新节点注解时的日志提示词
无
辛苦各位审核一下
无
> 修复更新节点注解时的日志提示词

- charts/hami/templates/scheduler/device-configmap.yaml
- charts/hami/values.yaml
- examples/metax/sgpu/allocate_specific_gpu.yaml
- examples/metax/sgpu/enable_topology_aware.yaml
- pkg/device/metax/config.go
- pkg/device/metax/protocol.go
- pkg/device/metax/protocol_test.go
- pkg/device/metax/score.go
- pkg/device/metax/sdevice.go
- pkg/device/metax/sdevice_test.go
/kind feature
when sgpu allocate 100%core, it behaves exactly like a exclusive device that can take advantage of the inter-GPU topology. we can obtain better scheduling results by aware the topology.
Fixes #
> Support Metax sGPU topology aware

- .github/workflows/issue-translate.yaml
> add issue translate robot

- pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
- pkg/device-plugin/nvidiadevice/nvinternal/plugin/register_test.go
> fix: fix err which retrieved incorrect NUMA node information issue #1275

- AUTHORS.md
Welcome fyp711 to become a HAMi member
https://github.com/Project-HAMi/community/issues/25
Fixes #
> Welcome fyp711 to become a HAMi member
